/**
 * Badge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: justin.molineaux@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Badge) {
      root.Badge = {};
    }
    root.Badge.ProfileEntity = factory(root.Badge.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProfileEntity model module.
   * @module model/ProfileEntity
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ProfileEntity</code>.
   * Returns a list of all the profiles
   * @alias module:model/ProfileEntity
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ProfileEntity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfileEntity} obj Optional instance to populate.
   * @return {module:model/ProfileEntity} The populated <code>ProfileEntity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('first_name')) {
        obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
      }
      if (data.hasOwnProperty('last_name')) {
        obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
      }
      if (data.hasOwnProperty('linkedin_link')) {
        obj['linkedin_link'] = ApiClient.convertToType(data['linkedin_link'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * A unique identifier for this profile.
   * @member {module:model/ProfileEntity.IdEnum} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The first name of the person
   * @member {module:model/ProfileEntity.FirstNameEnum} first_name
   */
  exports.prototype['first_name'] = undefined;
  /**
   * The last name of the person
   * @member {module:model/ProfileEntity.LastNameEnum} last_name
   */
  exports.prototype['last_name'] = undefined;
  /**
   * The URL of the person's LinkedIn profile
   * @member {module:model/ProfileEntity.LinkedinLinkEnum} linkedin_link
   */
  exports.prototype['linkedin_link'] = undefined;
  /**
   * The date and time (UTC, iso8601) at which the profile was created
   * @member {module:model/ProfileEntity.CreatedAtEnum} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * The date and time (UTC, iso8601) at which the profile was updated
   * @member {module:model/ProfileEntity.UpdatedAtEnum} updated_at
   */
  exports.prototype['updated_at'] = undefined;


  /**
   * Allowed values for the <code>id</code> property.
   * @enum {String}
   * @readonly
   */
  exports.IdEnum = {
    /**
     * value: "c4dd199e-f117-4ad4-98d0-7db4b5f762d5"
     * @const
     */
    "7db4b5f762d5": "c4dd199e-f117-4ad4-98d0-7db4b5f762d5"  };

  /**
   * Allowed values for the <code>first_name</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FirstNameEnum = {
    /**
     * value: "Jane"
     * @const
     */
    "Jane": "Jane"  };

  /**
   * Allowed values for the <code>last_name</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LastNameEnum = {
    /**
     * value: "Doe"
     * @const
     */
    "Doe": "Doe"  };

  /**
   * Allowed values for the <code>linkedin_link</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LinkedinLinkEnum = {
    /**
     * value: "https://www.linkedin.com/in/janedoe/"
     * @const
     */
    "https://www.linkedin.com/in/janedoe/": "https://www.linkedin.com/in/janedoe/"  };

  /**
   * Allowed values for the <code>created_at</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CreatedAtEnum = {
    /**
     * value: "2018-11-27T23:59:59.000Z"
     * @const
     */
    "000Z": "2018-11-27T23:59:59.000Z"  };

  /**
   * Allowed values for the <code>updated_at</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UpdatedAtEnum = {
    /**
     * value: "2018-11-27T23:59:59.000Z"
     * @const
     */
    "000Z": "2018-11-27T23:59:59.000Z"  };


  return exports;
}));


