/**
 * Badge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: justin.molineaux@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthenticationErrorEntity', 'model/ErrorEntity', 'model/ProfileEntity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AuthenticationErrorEntity'), require('../model/ErrorEntity'), require('../model/ProfileEntity'));
  } else {
    // Browser globals (root is window)
    if (!root.BadgeApi) {
      root.BadgeApi = {};
    }
    root.BadgeApi.ProfilesApi = factory(root.BadgeApi.ApiClient, root.BadgeApi.AuthenticationErrorEntity, root.BadgeApi.ErrorEntity, root.BadgeApi.ProfileEntity);
  }
}(this, function(ApiClient, AuthenticationErrorEntity, ErrorEntity, ProfileEntity) {
  'use strict';

  /**
   * Profiles service.
   * @module api/ProfilesApi
   * @version 0.0.1
   */

  /**
   * Constructs a new ProfilesApi. 
   * @alias module:api/ProfilesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getV1Profiles operation.
     * @callback module:api/ProfilesApi~getV1ProfilesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProfileEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Profiles
     * Returns a list of all the profiles
     * @param {String} authorization An API token that authenticates and authorizes an API user. Passed as &#39;Authorization: [api_token]&#39;.
     * @param {module:api/ProfilesApi~getV1ProfilesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProfileEntity}
     */
    this.getV1Profiles = function(authorization, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getV1Profiles");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ProfileEntity;

      return this.apiClient.callApi(
        '/v1/profiles', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
