/**
 * Badge API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: justin.molineaux@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthenticationErrorEntity', 'model/ErrorEntity', 'model/ProfileEntity', 'api/ProfilesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AuthenticationErrorEntity'), require('./model/ErrorEntity'), require('./model/ProfileEntity'), require('./api/ProfilesApi'));
  }
}(function(ApiClient, AuthenticationErrorEntity, ErrorEntity, ProfileEntity, ProfilesApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var BadgeApi = require('index'); // See note below*.
   * var xxxSvc = new BadgeApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new BadgeApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new BadgeApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new BadgeApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AuthenticationErrorEntity model constructor.
     * @property {module:model/AuthenticationErrorEntity}
     */
    AuthenticationErrorEntity: AuthenticationErrorEntity,
    /**
     * The ErrorEntity model constructor.
     * @property {module:model/ErrorEntity}
     */
    ErrorEntity: ErrorEntity,
    /**
     * The ProfileEntity model constructor.
     * @property {module:model/ProfileEntity}
     */
    ProfileEntity: ProfileEntity,
    /**
     * The ProfilesApi service constructor.
     * @property {module:api/ProfilesApi}
     */
    ProfilesApi: ProfilesApi
  };

  return exports;
}));
